branches:
  - name: main
    protection:
      merge_queue:
        enabled: true
        merge_method: squash # or 'merge' or 'rebase'
        build_concurrency: 3
        max_entries_to_build: 5
        min_entries_to_merge: 1
        max_entries_to_merge: 5
        wait_time_in_minutes: 5 # Wait before merging to batch PRs
